import type { Language } from "./language";

export const RESIDENCY_COPY = {
  en: {
    status: "Access opened. Origen Residency invitation.",
    brandLabel: "Origen — return to the opening gateway",
    availability: "10 spots available",
    tagline: "Surrendering to the human essence",
    title: ["Origen", "Residency"],
    details: [
      { term: "Duration", value: "5 days" },
      {
        term: "Dates",
        value: "09—14 Sept",
        ariaLabel: "September 9 to 14",
      },
      { term: "Place", value: "Liencres, Spain" },
    ],
    programEyebrow: "Five days together",
    programTitle: "The residency",
    experiences: [
      "Nature adventures",
      "Ecstatic Dance",
      "Contact Improv",
      "Tantric nights under the stars",
      "Cocreated experiences",
      "Open Doors Day",
    ],
    linksLabel: "Residency links",
    stay: "Stay",
    space: "Space",
    location: "Liencres, Spain",
    maps: "Maps",
    story: "Story",
    vision: "Vision",
    joinEyebrow: "Application form",
    join: "JOIN",
    interestEyebrow: "WhatsApp",
    interest: "INTERESTED",
    footerLocation: "Origen · Liencres",
    footerDate: "09—14 September",
    reset: "reset session",
  },
  es: {
    status: "Acceso concedido. Invitación a la Residencia Origen.",
    brandLabel: "Origen — volver al acceso inicial",
    availability: "10 plazas disponibles",
    tagline: "Un espacio para que la esencia emerja.",
    title: ["Residencia", "Origen"],
    details: [
      { term: "Duración", value: "5 días" },
      {
        term: "Fechas",
        value: "09—14 Sept",
        ariaLabel: "Del 9 al 14 de septiembre",
      },
      { term: "Lugar", value: "Liencres, España" },
    ],
    programEyebrow: "Cinco días juntos",
    programTitle: "La residencia",
    experiences: [
      "Aventuras en la naturaleza",
      "Danza extática",
      "Contact Improvisación",
      "Noches tántricas bajo las estrellas",
      "Experiencias cocreadas",
      "Día de puertas abiertas",
    ],
    linksLabel: "Enlaces de la residencia",
    stay: "Alojamiento",
    space: "Espacio",
    location: "Liencres, España",
    maps: "Mapa",
    story: "Historia",
    vision: "Visión",
    joinEyebrow: "Formulario de inscripción",
    join: "UNIRME",
    interestEyebrow: "WhatsApp",
    interest: "ME INTERESA",
    footerLocation: "Origen · Liencres",
    footerDate: "09—14 Septiembre",
    reset: "reiniciar sesión",
  },
} as const satisfies Record<Language, object>;

export const SPACE_COPY = {
  en: {
    status: "Access opened. Welcome to Origen Space.",
    brandLabel: "Origen — return to the opening gateway",
    availability: "Private retreat space",
    tagline: "Held by ocean, forest and living green",
    title: ["Origen", "Space"],
    details: [
      { term: "Setting", value: "Ocean & forest" },
      { term: "Land", value: "Costa Quebrada" },
      { term: "Place", value: "Liencres, Spain" },
    ],
    programEyebrow: "A privileged land by the sea",
    programTitle: "The space",
    programDescription:
      "A private retreat space rooted in a privileged landscape, where the Atlantic Ocean, coastal forest and abundant green meet. A home created for slowing down, gathering with intention and returning to what is essential.",
    experiences: [
      "A home for intimate retreats and gatherings",
      "Wild ocean and coastal paths at the doorstep",
      "Forest, gardens and living green",
      "Rooms for rest, movement and shared practice",
      "Silence, open horizons and space to breathe",
      "A place for cocreated experiences",
    ],
    linksLabel: "Origen Space links",
    stay: "The retreat",
    space: "Space",
    location: "Liencres, Spain",
    maps: "Maps",
    story: "Story",
    vision: "Vision",
    joinEyebrow: "Application form",
    join: "JOIN",
    interestEyebrow: "WhatsApp",
    interest: "INTERESTED",
    footerLocation: "Origen · Liencres",
    footerDate: "Ocean · Forest · Land",
    reset: "reset session",
  },
  es: {
    status: "Acceso concedido. Bienvenido al Espacio Origen.",
    brandLabel: "Origen — volver al acceso inicial",
    availability: "Espacio de retiro privado",
    tagline: "Sostenido por el océano, el bosque y la naturaleza viva",
    title: ["Espacio", "Origen"],
    details: [
      { term: "Entorno", value: "Océano y bosque" },
      { term: "Tierra", value: "Costa Quebrada" },
      { term: "Lugar", value: "Liencres, España" },
    ],
    programEyebrow: "Una tierra privilegiada junto al mar",
    programTitle: "El espacio",
    programDescription:
      "Un espacio de retiro privado arraigado en un paisaje privilegiado, donde se encuentran el océano Atlántico, el bosque costero y una naturaleza verde y abundante. Un hogar creado para bajar el ritmo, reunirse con intención y regresar a lo esencial.",
    experiences: [
      "Un hogar para retiros íntimos y encuentros",
      "Océano salvaje y senderos costeros a pocos pasos",
      "Bosque, jardines y naturaleza viva",
      "Estancias para descansar, moverse y practicar juntos",
      "Silencio, horizontes abiertos y espacio para respirar",
      "Un lugar para experiencias cocreadas",
    ],
    linksLabel: "Enlaces del Espacio Origen",
    stay: "El retiro",
    space: "Espacio",
    location: "Liencres, España",
    maps: "Mapa",
    story: "Historia",
    vision: "Visión",
    joinEyebrow: "Formulario de solicitud",
    join: "UNIRME",
    interestEyebrow: "WhatsApp",
    interest: "ME INTERESA",
    footerLocation: "Origen · Liencres",
    footerDate: "Océano · Bosque · Tierra",
    reset: "reiniciar sesión",
  },
} as const satisfies Record<Language, object>;

export const EDITORIAL_COPY = {
  story: {
    en: {
      chapter: "Chapter 01",
      title: "Story",
      paragraphs: [
        "After three years of designing, and trying to make it happen, this place is finally coming to life, a vision I’ve carried since I was 15.",
        "A home where I can invite friends over, turn up some badass music, jump and play. After a long process, I’m finally finishing a space that I will call home.",
        "I feel incredibly privileged to be on my dad’s land, a home he created himself. He discovered this place after I had been born, searching for somewhere safer than his house in the mountains, a place where his son could explore, and freely play.",
        "And now, all these years I would love you to be part of it.",
      ],
      nextPage: "vision" as const,
      nextLabel: "Vision",
    },
    es: {
      chapter: "Capítulo 01",
      title: "Historia",
      paragraphs: [
        "Después de tres años diseñando e intentando hacerlo realidad, este lugar por fin está cobrando vida: una visión que llevo conmigo desde los 15 años.",
        "Un hogar donde pueda invitar a mis amigos, poner música increíble a todo volumen, saltar y jugar. Después de un largo proceso, por fin estoy terminando un espacio al que llamaré hogar.",
        "Me siento increíblemente privilegiado de estar en la tierra de mi padre, en un hogar que él mismo creó. Descubrió este lugar después de que yo naciera, mientras buscaba un sitio más seguro que su casa en las montañas; un lugar donde su hijo pudiera explorar y jugar con libertad.",
        "Y ahora, después de todos estos años, me encantaría que formaras parte de él.",
      ],
      nextPage: "vision" as const,
      nextLabel: "Visión",
    },
  },
  vision: {
    en: {
      chapter: "Chapter 02",
      title: "Vision",
      paragraphs: [
        "Origen was born from a lived experience. Leaving home, spending years far from one’s roots, and discovering different ways of living, relating, listening, and nourishing oneself. And, eventually, returning.",
        "From that journey arose the desire to continue living fully, along with an intimate need to create a space where others could experience something profoundly human. The return to their own nature.",
        "This place lies in the heart of Costa Quebrada, a land of cliffs whose layers began forming beneath the earth more than one hundred million years ago. Over time, tectonic movements between Africa and the Iberian Peninsula lifted those layers, shaping the landscape that now stretches along the coast.",
        "Since then, the sea, the wind, and time itself have slowly revealed what had always been held within. Closer to the origins of the Earth.",
        "This landscape becomes a metaphor for the space itself. Just as the rock emerges from beneath its layers, our essence also rises gradually when it is given the space to reveal itself.",
        "This home is designed to hold that same process.",
        "A place close to the earth, where we can allow all that we are, beneath every layer, to emerge as we reconnect with our origin.",
      ],
      nextPage: "story" as const,
      nextLabel: "Story",
    },
    es: {
      chapter: "Capítulo 02",
      title: "Visión",
      paragraphs: [
        "Origen nació de una experiencia vivida. Dejar el hogar, pasar años lejos de las propias raíces y descubrir distintas formas de vivir, relacionarse, escuchar y nutrirse. Y, finalmente, regresar.",
        "De ese viaje surgió el deseo de seguir viviendo plenamente, junto con una necesidad íntima de crear un espacio donde otros pudieran experimentar algo profundamente humano. El regreso a su propia naturaleza.",
        "Este lugar se encuentra en el corazón de Costa Quebrada, una tierra de acantilados cuyas capas comenzaron a formarse bajo la tierra hace más de cien millones de años. Con el tiempo, los movimientos tectónicos entre África y la península ibérica elevaron esas capas y dieron forma al paisaje que hoy se extiende a lo largo de la costa.",
        "Desde entonces, el mar, el viento y el propio tiempo han ido revelando lentamente lo que siempre había permanecido en su interior. Más cerca de los orígenes de la Tierra.",
        "Este paisaje se convierte en una metáfora del propio espacio. Del mismo modo que la roca emerge desde debajo de sus capas, nuestra esencia también surge gradualmente cuando se le ofrece el espacio para revelarse.",
        "Este hogar está diseñado para sostener ese mismo proceso.",
        "Un lugar cerca de la tierra, donde podamos permitir que todo lo que somos, bajo cada capa, emerja mientras reconectamos con nuestro origen.",
      ],
      nextPage: "story" as const,
      nextLabel: "Historia",
    },
  },
} as const;

export const SHARED_EDITORIAL_COPY = {
  en: {
    brandLabel: "Origen — return to the opening gateway",
    returnTop: "Residency",
    navigationLabel: "Origen pages",
    returnTo: "Return to",
    continueTo: "Continue to",
    residency: "Residency",
    space: "Space",
    footer: "Spain · 2026",
  },
  es: {
    brandLabel: "Origen — volver al acceso inicial",
    returnTop: "Residencia",
    navigationLabel: "Páginas de Origen",
    returnTo: "Volver a",
    continueTo: "Continuar a",
    residency: "Residencia",
    space: "Espacio",
    footer: "España · 2026",
  },
} as const satisfies Record<Language, object>;
